name: cmake

on: [push, pull_request]

jobs:
  cmake-compile:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.16.x'
      - name: Use cmake
        run: |
          cmake .
